<?php

namespace Http\Controllers;

use Illuminate\Http\RedirectResponse;
use Modules\Exercise02\Http\Controllers\Exercise02Controller;
use Modules\Exercise02\Http\Requests\ATMRequest;
use Modules\Exercise02\Services\ATMService;
use Tests\TestCase;

class Exercise02ControllerTest extends TestCase
{
    protected $exercise02Controller;
    protected $atmService;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->atmService = $this->mock(ATMService::class);
        $this->exercise02Controller = new Exercise02Controller($this->atmService);
    }

    public function test_index()
    {
        $result = $this->exercise02Controller->index();
        $this->assertEquals('exercise02::index', $result->getName());
    }

    public function test_take_atm_fee()
    {
        $atmRequest = $this->mock(ATMRequest::class);
        $atmRequest->shouldReceive('validated')->andReturn([
            'card_id' => '1111',
        ]);
        $this->atmService->shouldReceive('calculate')->andReturn(0);
        $result = $this->exercise02Controller->takeATMFee($atmRequest);
        $this->assertInstanceOf(RedirectResponse::class, $result);
    }
}
